### ISSUE TITLE
Support DESTDIR in Makefile?

### ISSUE THREAD

**Issue by ghost** [Yuubi-san/unaesgcm#1]
When installing the software system-wide, it is more common to install the binaries to `/usr/bin/`.

Could you consider supporting the DESTDIR option in you Makefile? It would make package maintainers' work simpler.

**Comment by Yuubi-san** [comment]
Support for specifying the install location is on the roadmap from the very beginning. In fact, the only reason it wasn't implemented right from the start is one hardcoded path in the wrapper script. :D Which isn't really hard to deal with, and I guess now I'll get to it sooner rather than later.

By the way, this is the first I hear of [`DESTDIR`](https://www.gnu.org/prep/standards/html_node/DESTDIR.html), thanks for bringing it up. I never really dealt with packaging before and always used `prefix` alone.

**Comment by Yuubi-san** [comment]
Yyyeah, it was a bit more involved than I remembered. Anyway, this should be implemented by 0c7baf2 now, please try it out.

I'm guessing, the `mimeinfo.cache` file touched by `update-desktop-database` during installation would also be a bit of an annoyance when packaging? But that's a separate matter.

**Comment by Yuubi-san** [comment]
I'm closing this now. Reopen if there's still something to do.

**Comment by ghost** [comment]
Thank you!
